export const stickyCardsData = [
  {
    index: 1,
    title: "FORM",
    subtitle: "Creative Design & Campaigns",
    tagline: "Brands aren’t built. They’re strategically crafted.",
    description: "We develop cohesive brand identities and integrated campaigns that align strategy, design, and storytelling to drive measurable impact.",
    images: ["/form/serv-2.jpg", "/form/serv-1.jpg"],
    listTitle: "Expertise",
    listItems: ["Brand Identity & Language", "360° Campaigns", "Packaging & Print", "Creative Strategy & Art Direction", "Digital-First Storytelling"],
    footer: "Thoughtful design. Strategic execution.",
    id: "form",
  },
    {
    index: 2,
    title: "FRAME",
    subtitle: "Product Photography & Films",
    tagline: "Light is our language. Emotion is our focus.",
    description: "We create visually compelling photography and films that bring products to life. Every frame is carefully composed to highlight form, texture, and movement.",
    images: ["/frame/serv-1.jpg", "/frame/serv-2.jpg"],
    listTitle: "What We Shoot",
    listItems: ["Luxury Products", "Fashion & Apparel", "Tech & Lifestyle", "Food & Beverage", "Jewellery & Beauty", "Corporate Brand Films"],
    footer: "Because every product deserves a story worth seeing.",
    id: "frame",
  },
  {
    index: 3,
    title: "STAGE",
    subtitle: "Event Design and Management",
    tagline: "We don’t just plan events. We create experiences.",
    description: "From corporate launches to cultural galas, we transform spaces into immersive brand stories that leave a lasting impression.",
    images: ["/stage/serv-1.jpg", "/stage/serv-2.jpg"],
    listTitle: "Our Capabilities",
    listItems: ["Event Design & Creative Direction", "Stage & Spatial Aesthetics", "Décor & Production Management", "Speaker Planning & Flow", "Entertainment & Multimedia"],
    footer: "We design the atmosphere. We deliver the memory.",
    id: "stage",
  },
  {
    index: 4,
    title: "VOW",
    subtitle: "Emotion, captured forever.",
    tagline: "Refined design for timeless weddings.",
    description: "We blend cinematic storytelling with refined design to transform weddings into timeless works of art, crafted with elegance and intention.",
    images: ["/vow/serv-1.jpg", "/vow/serv-2.jpg"],
    listTitle: "Visual Highlights",
    listItems: ["Cinematic wedding stills", "Curated floral aesthetics", "Aerial drone moments", "Editorial couple portraits"],
    footer: "Because your love deserves nothing less than cinema.",
    id: "vow",
  },
  {
    index: 5,
    title: "GESTURE",
    subtitle: "Corporate Gifting",
    tagline: "Thoughtfulness is the new luxury.",
    description: "We curate bespoke corporate gifting experiences that reflect emotion, refinement, and brand intent as a powerful touchpoint.",
    images: ["/gesture/serv-2.jpg", "/gesture/serv-1.png"],
    listTitle: "What We Create",
    listItems: ["Custom Hampers", "Luxury Gift Sets", "Branded Premium Merchandise", "Seasonal & Festive Boxes", "Employee & VIP Gifting Programs"],
    footer: "Where meaningful giving meets strategic branding.",
    id: "gesture",
  },
  {
    index: 6,
    title: "VOICE",
    subtitle: "Consulting & Digital PR",
    tagline: "Where story meets strategy.",
    description: "We shape the narrative architecture that brands grow on — connecting businesses to investors and global media.",
    images: ["/voice/serv-2.jpg", "/voice/serv-1.jpg"],
    listTitle: "What We Do",
    listItems: ["Brand Consulting", "Investor-Ready Storytelling", "Business Positioning", "Digital PR & Media Presence", "Reputation Design", "Thought Leadership"],
    footer: "Your story, strategically amplified.",
    id: "voice",
  },
];